//! `maintenance::tests::backup` — the card-37 S4 backup bundle and arms (ADR-0064 D-H, D-I, D-J, D-V as amended by
//!   section 10 and 10.11 A, C, G, I): the pinned image, the archive contract, the conf keys, the run order with the
//!   refuse-before-write budget, verification and label identity, expire only after VERIFIED, retention 2, the
//!   repository on its own filesystem, the weak-subkey check and the env-file wrapper. Each test names the fault that
//!   turns it red.
//! Depends-on: crates=[postgres, serde_json]; services=[subprocess(sh), subprocess(humaux-maintenance),
//!   PostgreSQL(owner) r=[ops.backup_receipts, ops.backup_sets, ops.wal_archive_failures]]; env=[
//!   CARGO_BIN_EXE_humaux-maintenance, HOME,
//!   HUMAUX_MAINTENANCE_BACKUP_MIN_FREE_BYTES, HUMAUX_MAINTENANCE_BACKUP_REPO_MAX_BYTES, HUMAUX_PG_PORT, PATH];
//!   modules=[maintenance::tests::support::containers, maintenance::tests::support::throwaway]
//! Called-by: [cargo-test]
//! Invariants: [receipts go to a throwaway database humaux_thread_c37_bk_<pid>_<n> on the dev cluster, the backed-up
//!   cluster is a scratch project humaux-c37-<purpose>-<pid>-<n> from deploy/compose/backup.yml; both are removed by
//!   their guards on every path; the shared dev database and containers are never touched; one scratch source at a
//!   time; every throwaway secret is generated by the support module and never printed]
//! Spec: Baseline §44; §79.2; ADR-0064 D-H; ADR-0064 D-I; ADR-0064 D-J; ADR-0064 D-K; ADR-0064 D-V; ADR-0064 E17

#[path = "support/throwaway.rs"]
#[allow(dead_code)]
mod throwaway;

#[path = "support/containers.rs"]
#[allow(dead_code)]
mod containers;

use std::process::Output;
use std::time::Duration;

use containers::{Source, both, random_hex, root};
use serde_json::Value;

const RECEIPTS: &str = "c37_bk";

/// The arm's one JSON receipt (the last stdout line).
fn receipt(out: &Output) -> Value {
    let stdout = String::from_utf8_lossy(&out.stdout);
    let last = stdout.lines().last().unwrap_or("");
    serde_json::from_str(last).unwrap_or_else(|e| panic!("receipt json ({e}): {}", both(out)))
}

fn code(out: &Output) -> i32 {
    out.status.code().unwrap_or(-1)
}

/// `(label, outcome, failure)` of every receipt, oldest first.
fn receipts(db: &mut throwaway::Db) -> Vec<(Option<String>, String, Option<String>)> {
    db.client()
        .query(
            "SELECT backup_label, outcome, failure FROM ops.backup_receipts ORDER BY recorded_at",
            &[],
        )
        .expect("receipts")
        .iter()
        .map(|r| (r.get(0), r.get(1), r.get(2)))
        .collect()
}

fn count(db: &mut throwaway::Db, table: &str) -> i64 {
    db.client()
        .query_one(&format!("SELECT count(*) FROM {table}"), &[])
        .expect("count")
        .get(0)
}

/// Every repo_class / notice surface of a receipt (ADR-0064 10.2).
fn assert_local_only(r: &Value) {
    assert_eq!(r["repo_class"], "local_only", "{r}");
    assert!(
        r["notice"]
            .as_str()
            .is_some_and(|n| n.starts_with("NOT OFFSITE") && n.contains("host loss = total loss")),
        "{r}"
    );
}

/// Live `key=value` lines of the conf, comments and blank lines dropped, with their section.
fn conf_lines() -> Vec<(String, String)> {
    let conf =
        std::fs::read_to_string(root().join("deploy/pgbackrest/pgbackrest.conf")).expect("conf");
    let mut section = String::new();
    let mut out = Vec::new();
    for line in conf
        .lines()
        .map(|l| l.split('#').next().unwrap_or("").trim())
        .filter(|l| !l.is_empty())
    {
        if line.starts_with('[') {
            section = line.to_owned();
        } else {
            out.push((section.clone(), line.to_owned()));
        }
    }
    out
}

/// T-H6 (10.11 I, no Docker): the arms' stanza const names a section of the conf, and the six keys the budget, the
/// WAL bound, retention and encryption rest on are exactly as ruled. Faults: rename the `[humaux]` section; delete or
/// change any one of the six keys → red.
#[test]
fn the_stanza_const_matches_the_conf() {
    let src =
        std::fs::read_to_string(root().join("bins/maintenance/src/backup.rs")).expect("backup.rs");
    let stanza = src
        .lines()
        .find_map(|l| l.trim().strip_prefix("pub const STANZA: &str = \""))
        .and_then(|rest| rest.strip_suffix("\";"))
        .expect("pub const STANZA in backup.rs");
    let lines = conf_lines();
    assert!(
        lines
            .iter()
            .any(|(section, _)| *section == format!("[{stanza}]")),
        "the conf has a [{stanza}] section"
    );
    for key in [
        "archive-push-queue-max=2GiB",
        "archive-async=n",
        "expire-auto=n",
        "repo1-retention-full=2",
        "repo1-cipher-type=aes-256-cbc",
        "repo1-bundle=y",
    ] {
        let name = key.split('=').next().unwrap_or(key);
        let live: Vec<&String> = lines
            .iter()
            .filter(|(s, l)| s == "[global]" && l.split('=').next() == Some(name))
            .map(|(_, l)| l)
            .collect();
        assert_eq!(live, [key], "[global] {name}");
    }
}

/// T-I1 (no Docker): `humaux-dr.sh` refuses a dr.env that is group-readable (exit 3, nothing run) and runs the arm
/// once the file is 0600. Under cron's `PATH=/usr/bin:/bin` it refuses by name (exit 3, not 127) until dr.env sets
/// `PATH` (runbook §11.1 step 2), then runs. Faults: drop the mode check → the 0640 file is sourced and the arm runs
/// → red; drop the PATH check → exit 127 → red.
#[test]
fn the_dr_wrapper_refuses_a_group_readable_env_file() {
    use std::os::unix::fs::PermissionsExt;
    let home = std::env::temp_dir().join(format!("humaux-c37-drenv-{}", std::process::id()));
    let bin = home.join("bin");
    std::fs::create_dir_all(home.join(".config/humaux")).expect("config dir");
    std::fs::create_dir_all(&bin).expect("bin dir");
    let link = bin.join("humaux-maintenance");
    let _ = std::fs::remove_file(&link);
    std::os::unix::fs::symlink(env!("CARGO_BIN_EXE_humaux-maintenance"), &link)
        .expect("symlink the binary");
    let env_file = home.join(".config/humaux/dr.env");
    std::fs::write(&env_file, "HUMAUX_C37_WRAPPER_PROBE=1\n").expect("dr.env");
    let with_bin = format!("{}:/usr/bin:/bin", bin.display());
    let run = |path: &str| {
        // dep: subprocess(sh) — the wrapper under test
        std::process::Command::new("sh")
            .arg(root().join("deploy/pgbackrest/humaux-dr.sh"))
            .arg("--metrics-families")
            .env_clear()
            .env("HOME", &home)
            .env("PATH", path)
            .output()
            .expect("run humaux-dr.sh")
    };
    std::fs::set_permissions(&env_file, std::fs::Permissions::from_mode(0o640))
        .expect("chmod 0640");
    let refused = run(&with_bin);
    std::fs::set_permissions(&env_file, std::fs::Permissions::from_mode(0o600))
        .expect("chmod 0600");
    let ran = run(&with_bin);
    // Cron's PATH: refused by name until dr.env carries PATH.
    let cron_refused = run("/usr/bin:/bin");
    std::fs::write(
        &env_file,
        format!("HUMAUX_C37_WRAPPER_PROBE=1\nPATH={with_bin}\n"),
    )
    .expect("dr.env with PATH");
    let cron_ran = run("/usr/bin:/bin");
    let _ = std::fs::remove_dir_all(&home);
    assert_eq!(code(&refused), 3, "0640 is refused: {}", both(&refused));
    assert!(
        both(&refused).contains("must be mode 600") && refused.stdout.is_empty(),
        "{}",
        both(&refused)
    );
    assert_eq!(code(&ran), 0, "0600 runs the arm: {}", both(&ran));
    assert!(
        String::from_utf8_lossy(&ran.stdout).contains("# TYPE"),
        "{}",
        both(&ran)
    );
    assert_eq!(code(&cron_refused), 3, "cron PATH: {}", both(&cron_refused));
    assert!(
        both(&cron_refused).contains("humaux-maintenance is not on PATH"),
        "{}",
        both(&cron_refused)
    );
    assert_eq!(code(&cron_ran), 0, "PATH from dr.env: {}", both(&cron_ran));
}

/// T-H1: the Dockerfile's base is the pinned digest in the one stage `pg`, pgBackRest is installed by exact version,
/// and the built image carries exactly that package and PostgreSQL 18.6. Fault: unpin the package version → red.
#[test]
fn the_image_is_pinned_and_carries_pgbackrest() {
    let dockerfile = std::fs::read_to_string(root().join("deploy/images/postgres/Dockerfile"))
        .expect("Dockerfile");
    let live: Vec<&str> = dockerfile
        .lines()
        .filter(|l| !l.trim_start().starts_with('#'))
        .collect();
    let from: Vec<&&str> = live.iter().filter(|l| l.starts_with("FROM ")).collect();
    assert_eq!(from.len(), 1, "one stage");
    let digest = from[0]
        .strip_prefix("FROM postgres:18.6@sha256:")
        .and_then(|r| r.strip_suffix(" AS pg"))
        .expect("FROM postgres:18.6@sha256:<digest> AS pg");
    assert!(
        digest.len() == 64 && digest.bytes().all(|b| b.is_ascii_hexdigit()),
        "{digest}"
    );
    let version = live
        .iter()
        .find_map(|l| l.strip_prefix("ARG PGBACKREST_VERSION="))
        .expect("ARG PGBACKREST_VERSION=<exact>");
    assert!(
        live.iter()
            .any(|l| l.contains("\"pgbackrest=${PGBACKREST_VERSION}\"")),
        "the install line pins the package to the ARG"
    );
    if !containers::docker_ready("the_image_is_pinned_and_carries_pgbackrest") {
        return;
    }
    let got = containers::docker(&[
        "run",
        "--rm",
        "--memory",
        "64m",
        containers::IMAGE,
        "sh",
        "-c",
        "dpkg-query -W -f '${Version}' pgbackrest; echo; pgbackrest version; postgres --version",
    ])
    .expect("run the image");
    let mut lines = got.lines();
    assert_eq!(lines.next(), Some(version), "installed package = the pin");
    let upstream = version.split('-').next().unwrap_or(version);
    assert_eq!(
        lines.next(),
        Some(format!("pgBackRest {upstream}").as_str())
    );
    assert!(lines.next().is_some_and(|l| l.contains("18.6")), "{got}");
}

/// T-H2: `archive-push` (archive-async=n) answers 0 for an already archived segment with the same content and refuses
/// the same name with other content, so PostgreSQL retries instead of recycling it. Fault: `archive-async=y` in the
/// conf → red.
#[test]
fn archive_push_refuses_a_same_name_segment_with_other_content() {
    let Some(source) = Source::start(
        "archive_push_refuses_a_same_name_segment_with_other_content",
        "th2",
        "",
    ) else {
        return;
    };
    source.stanza_create();
    let codes = source.sh(
        "set -u; G=/var/lib/postgresql/18/docker; S=$(psql -qAt -c 'select pg_walfile_name(pg_current_wal_lsn())'); \
         psql -qAt -c 'create table t(i int); insert into t values (1); select pg_switch_wal()' >/dev/null; sleep 2; \
         d=$(mktemp -d); mkdir -p $d/pg_wal/archive_status $d/global; cp $G/global/pg_control $d/global/; \
         cp $G/pg_wal/$S $d/pg_wal/; P=\"pgbackrest --stanza=humaux --pg1-path=$d --log-level-console=off archive-push\"; \
         $P $d/pg_wal/$S; a=$?; printf 'x' | dd of=$d/pg_wal/$S bs=1 seek=100000 conv=notrunc 2>/dev/null; \
         $P $d/pg_wal/$S; b=$?; rm -rf $d; echo $a $b",
    );
    let (same, other) = codes.split_once(' ').expect("two exit codes");
    assert_eq!(same, "0", "same name, same content");
    assert_ne!(other, "0", "same name, other content must be refused");
}

/// T-J2: `backup run` writes one VERIFIED local receipt (with every budget number) and binds the label's identity;
/// its receipt says local_only. Fault: record VERIFIED without running `pgbackrest verify` → the table refuses the
/// claim (no verify_exit) → red.
#[test]
fn backup_run_records_a_verified_local_receipt() {
    let Some(mut db) = throwaway::db("backup_run_records_a_verified_local_receipt", RECEIPTS)
    else {
        return;
    };
    let Some(source) = Source::start("backup_run_records_a_verified_local_receipt", "tj2", "")
    else {
        return;
    };
    source.stanza_create();
    source.seed("w", 8);
    let out = source.maintenance(&db.maintenance_dsn, &["backup", "run"], &[]);
    assert_eq!(code(&out), 0, "{}", both(&out));
    let r = receipt(&out);
    assert_local_only(&r);
    assert_eq!(r["outcome"], "VERIFIED", "{r}");
    let label = source.labels().pop().expect("one set");
    assert_eq!(r["backup_label"], label.as_str());
    let row = db
        .client()
        .query_one(
            "SELECT backup_label, outcome, verify_exit, repo_bytes, repo_free_bytes, set_repo_bytes, estimate_bytes, \
                    repo_max_bytes, min_free_bytes, manifest_sha256 = verified_manifest_sha256 FROM ops.backup_receipts",
            &[],
        )
        .expect("exactly one receipt");
    assert_eq!(
        row.get::<_, Option<String>>(0).as_deref(),
        Some(label.as_str())
    );
    assert_eq!(row.get::<_, String>(1), "VERIFIED");
    assert_eq!(row.get::<_, Option<i32>>(2), Some(0));
    for i in 3..=6 {
        assert!(
            row.get::<_, Option<i64>>(i).is_some_and(|b| b > 0),
            "column {i} > 0"
        );
    }
    assert_eq!(row.get::<_, Option<i64>>(7), Some(8 << 30));
    assert_eq!(row.get::<_, Option<i64>>(8), Some(1 << 20));
    assert_eq!(row.get::<_, Option<bool>>(9), Some(true));
    let sets: Vec<String> = db
        .client()
        .query("SELECT backup_label FROM ops.backup_sets", &[])
        .expect("sets")
        .iter()
        .map(|r| r.get(0))
        .collect();
    assert_eq!(sets, [label]);
}

/// T-J3: a byte flipped in a bundle of a verified set makes `backup verify` FAILED (exit 1). SP-1: pgBackRest's
/// `verify --set` exits 0 even then and reports `status: error`, so the arm must read the report. Fault: treat the
/// reported invalid status as a warning → VERIFIED → red.
#[test]
fn verify_fails_on_a_corrupted_repo_object_and_records_failed() {
    let Some(mut db) = throwaway::db(
        "verify_fails_on_a_corrupted_repo_object_and_records_failed",
        RECEIPTS,
    ) else {
        return;
    };
    let Some(source) = Source::start(
        "verify_fails_on_a_corrupted_repo_object_and_records_failed",
        "tj3",
        "",
    ) else {
        return;
    };
    source.stanza_create();
    source.seed("w", 8);
    let first = source.maintenance(&db.maintenance_dsn, &["backup", "run"], &[]);
    assert_eq!(code(&first), 0, "{}", both(&first));
    let label = source.labels().pop().expect("one set");
    let bundle = source
        .repo()
        .join(format!("backup/humaux/{label}/bundle/1"));
    let mut bytes = std::fs::read(&bundle).expect("bundle 1");
    bytes[1000] ^= 0xff;
    std::fs::write(&bundle, &bytes).expect("flip one byte");
    let out = source.maintenance(
        &db.maintenance_dsn,
        &["backup", "verify", "--label", &label],
        &[],
    );
    assert_eq!(code(&out), 1, "{}", both(&out));
    let r = receipt(&out);
    assert_local_only(&r);
    assert_eq!(r["outcome"], "FAILED", "{r}");
    assert_eq!(
        receipts(&mut db).last().cloned(),
        Some((
            Some(label),
            "FAILED".to_owned(),
            Some("verify_invalid".to_owned())
        ))
    );
}

/// T-J4: `backup status` writes nothing (receipt, set and latch counts unchanged) and prints the class, the notice,
/// the newest VERIFIED set and the PITR window. Fault: status writes a receipt → red.
#[test]
fn backup_status_is_read_only() {
    let Some(mut db) = throwaway::db("backup_status_is_read_only", RECEIPTS) else {
        return;
    };
    let Some(source) = Source::start("backup_status_is_read_only", "tj4", "") else {
        return;
    };
    source.stanza_create();
    let run = source.maintenance(&db.maintenance_dsn, &["backup", "run"], &[]);
    assert_eq!(code(&run), 0, "{}", both(&run));
    let before = [
        count(&mut db, "ops.backup_receipts"),
        count(&mut db, "ops.backup_sets"),
        count(&mut db, "ops.wal_archive_failures"),
    ];
    let out = source.maintenance(&db.maintenance_dsn, &["backup", "status"], &[]);
    assert_eq!(code(&out), 0, "{}", both(&out));
    let after = [
        count(&mut db, "ops.backup_receipts"),
        count(&mut db, "ops.backup_sets"),
        count(&mut db, "ops.wal_archive_failures"),
    ];
    assert_eq!(before, after, "status wrote nothing");
    let r = receipt(&out);
    assert_local_only(&r);
    assert_eq!(
        r["newest_verified"]["backup_label"],
        source.labels().pop().expect("set").as_str(),
        "{r}"
    );
    assert_eq!(r["wal_archive_failing"], 0, "{r}");
    assert!(r["pitr_window_unbroken_since"].is_i64(), "{r}");
    assert!(
        r["headroom_bytes"]["repo_max"].is_i64() && r["headroom_bytes"]["free_floor"].is_i64(),
        "{r}"
    );
}

/// T-J5: a set's `backup.manifest` (and `.copy`) overwritten with another set's after its first verification fails
/// the next `backup verify` with `manifest_changed`, before pgBackRest's own verify runs. Fault: drop the label
/// identity compare → the failure is no longer `manifest_changed` → red.
#[test]
fn a_manifest_overwritten_after_verification_fails_the_next_verify() {
    let Some(mut db) = throwaway::db(
        "a_manifest_overwritten_after_verification_fails_the_next_verify",
        RECEIPTS,
    ) else {
        return;
    };
    let Some(source) = Source::start(
        "a_manifest_overwritten_after_verification_fails_the_next_verify",
        "tj5",
        "",
    ) else {
        return;
    };
    source.stanza_create();
    for _ in 0..2 {
        source.seed("w", 2);
        let out = source.maintenance(&db.maintenance_dsn, &["backup", "run"], &[]);
        assert_eq!(code(&out), 0, "{}", both(&out));
    }
    let labels = source.labels();
    assert_eq!(labels.len(), 2, "{labels:?}");
    let dir = |l: &str| source.repo().join(format!("backup/humaux/{l}"));
    for f in ["backup.manifest", "backup.manifest.copy"] {
        let other = std::fs::read(dir(&labels[1]).join(f)).expect("other set's manifest");
        std::fs::write(dir(&labels[0]).join(f), other).expect("overwrite");
    }
    let out = source.maintenance(
        &db.maintenance_dsn,
        &["backup", "verify", "--label", &labels[0]],
        &[],
    );
    assert_eq!(code(&out), 1, "{}", both(&out));
    assert_eq!(receipt(&out)["failure"], "manifest_changed");
    let row = db
        .client()
        .query_one(
            "SELECT outcome, failure, verify_exit FROM ops.backup_receipts WHERE backup_label = $1 \
             ORDER BY recorded_at DESC LIMIT 1",
            &[&labels[0]],
        )
        .expect("newest receipt of the set");
    assert_eq!(row.get::<_, String>(0), "FAILED");
    assert_eq!(
        row.get::<_, Option<String>>(1).as_deref(),
        Some("manifest_changed")
    );
    assert_eq!(
        row.get::<_, Option<i32>>(2),
        None,
        "pgBackRest's verify never ran"
    );
}

/// The shim of T-J7: a `pgbackrest` earlier on `PATH` that fails only `verify`, and only while the test's flag file
/// exists; every other command (archive-push included) is the real binary.
const VERIFY_SHIM: &str = "#!/bin/sh\nif [ -e /var/lib/pgbackrest/fail-verify ]; then\n  for a in \"$@\"; do\n    [ \"$a\" = verify ] && { echo 'shim: verify fails'; exit 1; }\n  done\nfi\nexec /usr/bin/pgbackrest \"$@\"\n";

/// T-J7: two VERIFIED runs, then a run whose verification fails: nothing is expired, so `info` lists three fulls
/// (E16 invariant 5). Fault: run expire unconditionally → two fulls → red.
#[test]
fn a_failed_verification_expires_nothing() {
    use std::os::unix::fs::PermissionsExt;
    let Some(mut db) = throwaway::db("a_failed_verification_expires_nothing", RECEIPTS) else {
        return;
    };
    let Some(source) = Source::prepare("a_failed_verification_expires_nothing", "tj7") else {
        return;
    };
    let shim = source.dir.join("pgbackrest-shim");
    std::fs::write(&shim, VERIFY_SHIM).expect("shim");
    std::fs::set_permissions(&shim, std::fs::Permissions::from_mode(0o755)).expect("chmod shim");
    source.restart(&format!(
        "services:\n  pg:\n    volumes:\n      - type: bind\n        source: {}\n        target: /usr/local/bin/pgbackrest\n        read_only: true\n",
        shim.display()
    ));
    source.stanza_create();
    for _ in 0..2 {
        source.seed("w", 2);
        let out = source.maintenance(&db.maintenance_dsn, &["backup", "run"], &[]);
        assert_eq!(code(&out), 0, "{}", both(&out));
    }
    std::fs::write(source.repo_dir.join("fail-verify"), "").expect("flag");
    let out = source.maintenance(&db.maintenance_dsn, &["backup", "run"], &[]);
    assert_eq!(code(&out), 1, "{}", both(&out));
    assert_eq!(receipt(&out)["failure"], "verify_exit:1");
    assert_eq!(
        source.labels().len(),
        3,
        "a failed verification expired a set"
    );
    let outcomes: Vec<String> = receipts(&mut db).into_iter().map(|r| r.1).collect();
    assert_eq!(outcomes, ["VERIFIED", "VERIFIED", "FAILED"]);
}

/// The T-J8 / T-J13 layout: the repository filesystem is a capped tmpfs (PGDATA stays on its volume).
fn tmpfs_layout(bytes: u64, env: &str, archive: bool, tcp: bool) -> String {
    let listen = if tcp { "*" } else { "" };
    let archiving = if archive {
        ", -c, wal_level=replica, -c, archive_mode=on, -c, archive_timeout=3600s, -c, \"archive_command=pgbackrest --stanza=humaux archive-push %p\""
    } else {
        ", -c, archive_mode=off"
    };
    format!(
        "services:\n  pg:\n    environment:\n{env}    volumes:\n      - type: tmpfs\n        target: /var/lib/pgbackrest\n        tmpfs:\n          size: {bytes}\n\
         \x20   command: [postgres, -c, max_wal_size=64MB, -c, min_wal_size=32MB{archiving}, -c, \"listen_addresses={listen}\"]\n"
    )
}

/// Bytes of a `du -sk` / `df -Pk` style figure inside `pg`.
fn kib(source: &Source, script: &str) -> i64 {
    source
        .sh(script)
        .trim()
        .parse::<i64>()
        .expect("a KiB figure")
        * 1024
}

/// Fills the repository filesystem with a test-owned file outside `repo/` until `free` bytes remain.
fn fill_to(source: &Source, free: i64) {
    let now = kib(
        source,
        "df -Pk /var/lib/pgbackrest | tail -1 | awk '{print $4}'",
    );
    assert!(now > free, "tmpfs too small: free {now} <= {free}");
    source.sh(&format!(
        "fallocate -l {} /var/lib/pgbackrest/filler",
        now - free
    ));
}

/// T-J8 (10.11 I): PGDATA on its volume, the repository on a 256 MiB tmpfs, a database of >= 64 MiB seeded with
/// archiving off, a filler that leaves less free than the first-backup estimate plus MIN_FREE: `backup run` refuses
/// `budget_free_floor` (exit 3) before writing — one FAILED receipt with a NULL label and the budget numbers, `repo/`
/// unchanged, PostgreSQL untouched and writable; with REPO_MAX = the current repository bytes it refuses
/// `budget_repo_max`. Fault: skip the estimate → the backup writes into the tmpfs (ENOSPC, exit 1, or changed
/// `repo/` bytes) → red.
#[test]
fn a_backup_that_would_break_the_budget_is_refused_before_writing() {
    const MIN_FREE: i64 = 32 << 20;
    let Some(mut db) = throwaway::db(
        "a_backup_that_would_break_the_budget_is_refused_before_writing",
        RECEIPTS,
    ) else {
        return;
    };
    let env = "      PGBACKREST_COMPRESS_TYPE: none\n";
    let Some(source) = Source::start(
        "a_backup_that_would_break_the_budget_is_refused_before_writing",
        "tj8",
        &tmpfs_layout(256 << 20, env, false, false),
    ) else {
        return;
    };
    source.seed("w", 72);
    source.restart(&tmpfs_layout(256 << 20, env, true, false));
    source.own_repo_mount();
    source.stanza_create();
    let estimate = kib(
        &source,
        "du -sk /var/lib/postgresql/18/docker/base | cut -f1",
    );
    assert!(estimate >= 64 << 20, "database >= 64 MiB: {estimate}");
    fill_to(&source, estimate + MIN_FREE - (8 << 20));
    let repo_before = source.sh("du -sk /var/lib/pgbackrest/repo | cut -f1");
    let started = source.psql("select pg_postmaster_start_time()");

    let out = source.maintenance(
        &db.maintenance_dsn,
        &["backup", "run"],
        &[(
            "HUMAUX_MAINTENANCE_BACKUP_MIN_FREE_BYTES",
            MIN_FREE.to_string(),
        )],
    );
    let all = both(&out);
    assert_eq!(code(&out), 3, "{all}");
    assert!(
        String::from_utf8_lossy(&out.stdout).contains("budget_free_floor:"),
        "{all}"
    );
    assert!(!all.contains("No space left on device"), "{all}");
    let row = db
        .client()
        .query_one(
            "SELECT outcome, failure LIKE 'budget_free_floor:%', backup_label IS NULL, repo_bytes IS NOT NULL, \
                    repo_free_bytes IS NOT NULL, estimate_bytes IS NOT NULL FROM ops.backup_receipts",
            &[],
        )
        .expect("exactly one receipt");
    assert_eq!(row.get::<_, String>(0), "FAILED");
    for i in 1..=5 {
        assert!(row.get::<_, bool>(i), "receipt column {i}");
    }
    assert_eq!(
        source.sh("du -sk /var/lib/pgbackrest/repo | cut -f1"),
        repo_before,
        "repo/ untouched"
    );
    assert_eq!(
        source.psql("select pg_postmaster_start_time()"),
        started,
        "PostgreSQL untouched"
    );
    source.psql("insert into w values (-1, 'still writable')");

    let repo_bytes = kib(&source, "du -sk /var/lib/pgbackrest/repo | cut -f1");
    let out = source.maintenance(
        &db.maintenance_dsn,
        &["backup", "run"],
        &[
            (
                "HUMAUX_MAINTENANCE_BACKUP_REPO_MAX_BYTES",
                repo_bytes.to_string(),
            ),
            ("HUMAUX_MAINTENANCE_BACKUP_MIN_FREE_BYTES", "1".to_owned()),
        ],
    );
    assert_eq!(code(&out), 3, "{}", both(&out));
    assert!(
        String::from_utf8_lossy(&out.stdout).contains("budget_repo_max:"),
        "{}",
        both(&out)
    );
    assert_eq!(
        source.sh("du -sk /var/lib/pgbackrest/repo | cut -f1"),
        repo_before,
        "repo/ untouched"
    );
    assert!(source.labels().is_empty(), "no set was written");
}

/// T-J13 (10.11 I, live leg of the WAL bound): the repository on a 96 MiB tmpfs left nearly full, the archive queue
/// capped at 64 MiB: archiving fails and PostgreSQL does not — every INSERT succeeds, the postmaster never restarts,
/// segments are dropped past the cap and `pg_wal` stays bounded (spike SP-10 measured the bound: queue max +
/// max_wal_size + three segments; SP-10 measured 144 MiB under the same caps). The latch (S6, 10.11 I): one
/// DR_EVIDENCE pass of the real daemon against the scratch cluster after the first failures reads
/// `wal_archive_failing 1`; after the drops (which PostgreSQL counts as archived) a second pass still reads 1 from
/// `ops.wal_archive_failures` (one row for the incident). Fault: drop the queue-max override (the conf's 2 GiB lets
/// `pg_wal` grow with every round) → red. The latch's own fault (a non-latched expression) is T-K3''s: here the
/// archiver is usually still failing at the second pass (measured), so that fault does not show at this leg.
#[test]
fn a_full_repo_filesystem_stops_archiving_not_postgres() {
    const BOUND: i64 = (64 + 64 + 3 * 16) << 20;
    let env = "      PGBACKREST_ARCHIVE_PUSH_QUEUE_MAX: 64MiB\n";
    let Some(source) = Source::start(
        "a_full_repo_filesystem_stops_archiving_not_postgres",
        "tj13",
        &tmpfs_layout(96 << 20, env, true, true),
    ) else {
        return;
    };
    source.own_repo_mount();
    // ADR-0064 D-K: the DR_EVIDENCE passes need the schema and a role_maintenance login on this scratch cluster.
    source.psql("CREATE DATABASE humaux_thread");
    // dep: PostgreSQL(owner) — migrate the scratch cluster's database (never the dev cluster)
    let mut owner = postgres::Client::connect(&source.owner_dsn("humaux_thread"), postgres::NoTls)
        .expect("scratch owner");
    throwaway::migrate_all(&mut owner);
    let password = random_hex();
    owner
        .batch_execute(&format!(
            "ALTER ROLE role_maintenance PASSWORD '{password}'"
        ))
        .expect("role_maintenance login");
    let dsn = format!(
        "postgres://role_maintenance:{password}@127.0.0.1:{}/humaux_thread",
        source.env_value("HUMAUX_PG_PORT")
    );
    source.stanza_create();
    fill_to(&source, 4 << 20);
    let started = source.psql("select pg_postmaster_start_time()");
    let mut max_wal = 0_i64;
    let mut round = |n: u32| {
        for _ in 0..n {
            source.seed("b", 12);
            source.psql("select pg_switch_wal()");
            let w: i64 = source
                .psql("select sum(size) from pg_ls_waldir()")
                .parse()
                .expect("pg_wal bytes");
            max_wal = max_wal.max(w);
        }
    };
    round(2);
    let failing = (0..20).any(|_| {
        std::thread::sleep(Duration::from_millis(500));
        source.psql("select coalesce(last_failed_time > coalesce(last_archived_time, '-infinity'), false) from pg_stat_archiver")
            == "t"
    });
    assert!(
        failing,
        "archiving fails once the repository filesystem is full"
    );
    // dep: subprocess(humaux-maintenance) — one DR_EVIDENCE pass of the real daemon against the scratch cluster
    let first = throwaway::dr_evidence_pass(&dsn, &source.repo_dir);
    assert_eq!(
        throwaway::sample_value(&first, "wal_archive_failing"),
        Some(1.0),
        "the first pass latches: {first}"
    );
    round(14);
    assert_eq!(
        source.psql("select pg_postmaster_start_time()"),
        started,
        "PostgreSQL never restarted"
    );
    assert!(max_wal <= BOUND, "pg_wal bounded: {max_wal} > {BOUND}");
    assert!(
        source.logs().contains("because archive queue exceeded"),
        "segments were dropped at the cap"
    );
    let second = throwaway::dr_evidence_pass(&dsn, &source.repo_dir);
    assert_eq!(
        throwaway::sample_value(&second, "wal_archive_failing"),
        Some(1.0),
        "still latched after the drops: {second}"
    );
    let rows: i64 = owner
        .query_one("SELECT count(*) FROM ops.wal_archive_failures", &[])
        .expect("latch rows")
        .get(0);
    assert_eq!(rows, 1, "one row for the incident");
}

/// T-J14 (10.11 A): with the repository mount on the pgdata volume, `backup check` exits 1 and `backup run` exits 3,
/// both `repo_shares_pgdata_fs`, and nothing is written under `repo/` by either arm. Fault: remove the `st_dev`
/// comparison → check runs pgBackRest / run backs up → red.
#[test]
fn backup_refuses_a_repo_on_the_pgdata_filesystem() {
    let Some(mut db) = throwaway::db("backup_refuses_a_repo_on_the_pgdata_filesystem", RECEIPTS)
    else {
        return;
    };
    let extra = "services:\n  pg:\n    volumes:\n      - pgdata:/var/lib/pgbackrest\n";
    let Some(source) = Source::start(
        "backup_refuses_a_repo_on_the_pgdata_filesystem",
        "tj14",
        extra,
    ) else {
        return;
    };
    let listing = "find /var/lib/pgbackrest/repo 2>/dev/null | sort | wc -l";
    let before = source.sh(listing);
    let check = source.maintenance("", &["backup", "check"], &[]);
    assert_eq!(code(&check), 1, "{}", both(&check));
    assert_eq!(receipt(&check)["failure"], "repo_shares_pgdata_fs");
    assert_local_only(&receipt(&check));
    let run = source.maintenance(&db.maintenance_dsn, &["backup", "run"], &[]);
    assert_eq!(code(&run), 3, "{}", both(&run));
    assert_eq!(receipt(&run)["reason"], "repo_shares_pgdata_fs");
    assert_eq!(source.sh(listing), before, "nothing written under repo/");
    assert_eq!(
        receipts(&mut db),
        [(
            None,
            "FAILED".to_owned(),
            Some("repo_shares_pgdata_fs".to_owned())
        )]
    );
}

/// T-J9 (+10.11 I): three VERIFIED runs leave exactly the two newest fulls in `info`, and `backup status` reports the
/// PITR window from the older of those two (not from the first receipt). Faults: `repo1-retention-full=3` → three
/// fulls → red; the window computed from receipts only → the first set's start → red.
#[test]
fn expire_keeps_exactly_the_two_newest_verified_fulls() {
    let Some(mut db) = throwaway::db(
        "expire_keeps_exactly_the_two_newest_verified_fulls",
        RECEIPTS,
    ) else {
        return;
    };
    let Some(source) = Source::start(
        "expire_keeps_exactly_the_two_newest_verified_fulls",
        "tj9",
        "",
    ) else {
        return;
    };
    source.stanza_create();
    let mut made = Vec::new();
    for _ in 0..3 {
        source.seed("w", 2);
        let out = source.maintenance(&db.maintenance_dsn, &["backup", "run"], &[]);
        assert_eq!(code(&out), 0, "{}", both(&out));
        let r = receipt(&out);
        made.push((
            r["backup_label"].as_str().expect("label").to_owned(),
            r["backup_started_at"].clone(),
        ));
    }
    assert_eq!(
        source.labels(),
        [made[1].0.clone(), made[2].0.clone()],
        "exactly the two newest"
    );
    let out = source.maintenance(&db.maintenance_dsn, &["backup", "status"], &[]);
    assert_eq!(code(&out), 0, "{}", both(&out));
    assert_eq!(
        receipt(&out)["pitr_window_unbroken_since"],
        made[1].1,
        "window from the older set present"
    );
    assert_eq!(count(&mut db, "ops.backup_receipts"), 3);
}

/// T-J12 (+10.11 G, I): `backup check` on the encrypted stanza prints `repo_cipher=aes-256-cbc` and `weak_subkeys=0`,
/// exits 0, and no subkey (a 64-character base64 run) appears anywhere in its output. Faults: print the `repo-get`
/// output → red; `repo1-cipher-type=none` → `repo_not_encrypted` → red.
#[test]
fn check_counts_weak_subkeys_without_printing_them() {
    let Some(source) = Source::start(
        "check_counts_weak_subkeys_without_printing_them",
        "tj12",
        "",
    ) else {
        return;
    };
    source.stanza_create();
    let out = source.maintenance("", &["backup", "check"], &[]);
    let all = both(&out);
    assert_eq!(code(&out), 0, "{all}");
    let stdout = String::from_utf8_lossy(&out.stdout);
    assert!(
        stdout.lines().any(|l| l == "repo_cipher=aes-256-cbc"),
        "{all}"
    );
    assert!(stdout.lines().any(|l| l == "weak_subkeys=0"), "{all}");
    assert_local_only(&receipt(&out));
    let mut run = 0;
    for b in all.bytes() {
        run = if b.is_ascii_alphanumeric() || b == b'+' || b == b'/' || b == b'=' {
            run + 1
        } else {
            0
        };
        assert!(
            run < 64,
            "a 64-character base64 run (a subkey?) in the output"
        );
    }
}
