[package]
name = "humaux-public-worker"
edition.workspace = true
version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
humaux-adapters = { path = "../../crates/adapters" }
humaux-domain = { path = "../../crates/domain" }
humaux-infra-cell = { path = "../../crates/infra-cell" }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
uuid = { version = "1.25.0", features = ["v7"] }
