-- Fixer-review follow-up to 0005_private_pipeline (T4.6+T4.7 consolidation worker review,
-- §11.9/§11.6): private.memory_rollups currently carries no Authority class at all and no
-- visibility scoping of its own — it only has (rollup_id, tenant_id, run_id, content,
-- created_at). Two independent gaps this migration closes:
--
-- 1. §11.9 "禁止 Rollup 自己成为比 source Memory 更高的 Authority" has nothing to constrain:
--    `application::consolidate::validate_rollup_before_publish` takes an `AuthorityClass` the
--    caller invents on the spot and never persists — this adds the column so a published
--    rollup's own Authority is a real, queryable fact, the same four-column shape
--    `private.memory_records` already uses (§59.1 G59-5), not a new convention.
-- 2. §11.6/§11.8's per-owner visibility (USER_PRIVATE/WORKSPACE_SHARED/TENANT_SHARED) is not
--    carried onto the rollup at all — 0012_rls.sql's blanket DO-loop caught `memory_rollups`
--    only because it has a bare `tenant_id` column, giving it a *tenant-only*
--    `memory_rollups_tenant_isolation` policy (verified live). A rollup that summarizes
--    WORKSPACE_SHARED or (once a future task scopes auto-consolidation to one visibility
--    owner) USER_PRIVATE memories must not become readable tenant-wide just because it landed
--    in this table — same three-branch shape §8.1/§6.1.1 already use on evidence_objects/
--    memory_records, applied here for the first time.
--
-- private.memory_rollups has zero rows in every environment this migration has run against
-- (verified live: `select count(*) from private.memory_rollups` = 0 — no shipped caller
-- inserts into it yet, `consolidate_repo::publish_rollup` is this task's own new code), so
-- every new column below goes straight to its final NOT NULL/CHECK shape in one step; there
-- is no existing row to backfill and no reason to defer tightening the way 0049 had to for a
-- table it could not assume was empty.

ALTER TABLE private.memory_rollups
  ADD COLUMN authority_class text NOT NULL DEFAULT 'PrivateKnowledge',
  ADD COLUMN visibility_class text NOT NULL DEFAULT 'TENANT_SHARED',
  ADD COLUMN visibility_user_id uuid REFERENCES control.users(user_id),
  ADD COLUMN visibility_workspace_id uuid REFERENCES control.workspaces(workspace_id);

-- Defaults above exist only to let `ADD COLUMN ... NOT NULL` succeed uniformly regardless of
-- row count at apply time (§46 discipline: do not special-case "table happens to be empty
-- today"); every future INSERT must supply its own real values instead of relying on them —
-- dropped immediately so a caller that forgets either column fails loudly at INSERT time
-- rather than silently landing the default.
ALTER TABLE private.memory_rollups ALTER COLUMN authority_class DROP DEFAULT;
ALTER TABLE private.memory_rollups ALTER COLUMN visibility_class DROP DEFAULT;

-- Same closed set as private.memory_records.authority_class (migrations/
-- 0004_private_evidence_memory.sql), quoted verbatim — a rollup's Authority is a value of
-- the same domain type, not a parallel enum.
ALTER TABLE private.memory_rollups
  ADD CONSTRAINT memory_rollups_authority_class_known CHECK (authority_class IN (
    'PublicKnowledge','PrivateKnowledge','UserPreference','ProjectDecision',
    'UserCorrection','ProjectConstraint','ExplicitTaskContext'));

-- Same three-branch visibility CHECK as private.memory_records
-- (memory_records_visibility_matches_class) — one non-NULL scoping column per class,
-- mutually exclusive and exhaustive.
ALTER TABLE private.memory_rollups
  ADD CONSTRAINT memory_rollups_visibility_matches_class CHECK (
    visibility_class IN ('USER_PRIVATE','WORKSPACE_SHARED','TENANT_SHARED')
    AND (
      (visibility_class = 'USER_PRIVATE' AND visibility_user_id IS NOT NULL AND visibility_workspace_id IS NULL)
      OR (visibility_class = 'WORKSPACE_SHARED' AND visibility_user_id IS NULL AND visibility_workspace_id IS NOT NULL)
      OR (visibility_class = 'TENANT_SHARED' AND visibility_user_id IS NULL AND visibility_workspace_id IS NULL)
    )
  );

-- Replace 0012_rls.sql's generic blanket tenant-only policy (`memory_rollups_tenant_isolation`,
-- auto-generated by that migration's DO-loop for any table with a bare `tenant_id` column)
-- with the combined tenant+visibility predicate — same shape as
-- `evidence_objects_tenant_and_visibility` (0012_rls.sql). One PERMISSIVE policy, not two:
-- Postgres ORs multiple PERMISSIVE policies together, so leaving the old tenant-only policy
-- in place alongside this one would let tenant membership alone satisfy the row check again,
-- silently re-opening the exact leak this migration closes.
DROP POLICY IF EXISTS memory_rollups_tenant_isolation ON private.memory_rollups;

CREATE POLICY memory_rollups_tenant_and_visibility ON private.memory_rollups
USING (
  tenant_id = current_setting('humaux.tenant_id', true)::uuid
  AND (
    visibility_class = 'TENANT_SHARED'
    OR (visibility_class = 'USER_PRIVATE'
        AND visibility_user_id = current_setting('humaux.user_id', true)::uuid)
    OR (visibility_class = 'WORKSPACE_SHARED'
        AND EXISTS (
          SELECT 1 FROM control.memberships m
          WHERE m.tenant_id = memory_rollups.tenant_id
            AND m.user_id = current_setting('humaux.user_id', true)::uuid
            AND m.state = 'ACTIVE'
        ))
  )
)
WITH CHECK (
  tenant_id = current_setting('humaux.tenant_id', true)::uuid
  AND (
    visibility_class = 'TENANT_SHARED'
    OR (visibility_class = 'USER_PRIVATE'
        AND visibility_user_id = current_setting('humaux.user_id', true)::uuid)
    OR (visibility_class = 'WORKSPACE_SHARED'
        AND EXISTS (
          SELECT 1 FROM control.memberships m
          WHERE m.tenant_id = memory_rollups.tenant_id
            AND m.user_id = current_setting('humaux.user_id', true)::uuid
            AND m.state = 'ACTIVE'
        ))
  )
);

-- role_consolidation_worker's existing table-level GRANT SELECT, INSERT ON
-- private.memory_rollups (0011_roles_and_grants.sql) already covers every column, including
-- these four new ones — no column-restricted grant exists on this table for any role
-- (verified: 0011's own GRANT list has no `GRANT ... (col, ...)` form here, unlike
-- memory_consolidation_runs), so no GRANT statement is needed in this migration.
